@host=http://localhost:5121

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNDE1Y2NhMS1mYTViLTQwZTEtYWNlMS1lY2ZkY2FkMDkwMWIiLCJnaXZlbl9uYW1lIjoiSmFzb24iLCJmYW1pbHlfbmFtZSI6IkhhbW1vY2siLCJqdGkiOiIyNDEzNjkwMy01YjlmLTRhNWItYTgyOC1mZjI2OTIyZTlhMzAiLCJleHAiOjE2NzIyNDc3NzUsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.G8siN56GYDTOm1kB2QtP-XcdjJhFDMxfNMNEMRRkKms